### ISSUE TITLE
Apply_connector needed between two add_connector calls in some cases

### ISSUE THREAD

**Issue by FabricioS** [pyphs/pyphs#30]
When using a connector-like element (like a 0 or 1 junction), I need to apply the first connector defined before I can add another connection
See [test case](https://gist.github.com/FabricioS/ae84f5e40e75ac6c6e02b61120fb2d4b) where two connections are added to a PHS core defined as the combination of three simple PHS. Whether apply_connectors is called between the two add_connector changes the resulting PHS.

In this case, the connective ports can be manually eliminated, and the result shows that apply_connector has to be called at intermediate step.

Any idea about why this occurs ?

**Comment by afalaize** [comment]
This is a very interesting case study. The reason for this behavior is **the connectors mechanism can be used only if the resulting submatrix Mcycy is 0**. This is because a robust, general way to recast the connection of two phs into the restrictive structure "b=M.a" is not available (and may not be feasible).

I draw your attention to the following facts:
- the connector mechanism is primarily intended to cope with the realizability analysis of graphs that include gyrators and transformers, so it may lack some strategic thinking to be used directly with PHSCore's;
- submatrix Myy can be dense, provided it splits into a skew-symmetric part Jyy and a positive symmetric part Ryy;
- changing a port to a connector port does not alter the structure of matrix M, since this change is simply a permutation of ports, i.e. a simple permutation of rows and columns of M, with total input "(u, cu)" and total output "(y, cy)" (see my implementation of your ''repr'' function below).

```python
def repr(obj):
    """
    Parameter
    ---------
    obj: pyphs.PHSCore

    Result
    ------
    sympy.pprint of PHSCore structure b = M.a with
    * b = [dx, w, y, cy].T
    * M = J - R
    * a = [dxH, z, u, cu].T
    """
    print("*"*80)
    print(obj.label)
    sy.pprint([mat(obj.dx() + obj.w + obj.y + obj.cy),
               obj.M,
               mat(obj.g() + obj.z + obj.u + obj.cu)])
```

All of this is not very clear, mainly beacause of (i) the lack of method documentation and (ii) the lack of assertions. So, I made two changes: (i) a [milestone](https://github.com/afalaize/pyphs/milestone/1) regarding the documentation and (ii) a [commit](https://github.com/afalaize/pyphs/commit/efebe00376d896a1eac3a52c4cf6b52cbf698fd5) that implement the assertion that submatrix Mcycy is 0.

I propose to close this issue since this is an expected behavior, and to open a new issue or milestone regarding the implementation of a robust connection method in the cases where Mcycy is different from 0. Surely your solver in the [test case](https://gist.github.com/FabricioS/ae84f5e40e75ac6c6e02b61120fb2d4b) is a great starting point.

**Comment by afalaize** [comment]
I made a [change in `apply_connectors`to account for **invertible** `core.Mcycy` matrix](https://github.com/afalaize/pyphs/commit/7323ebc249dd306cc3fe7788ba4655f20ff20be9). A [modified version of your test](https://gist.github.com/afalaize/f1165788c9d118f7dacbbd5dd7711884) passes:
* removing the forcing of skew symmetry of Jyy of obj3 (P_0 = P_2 = 0), since in the general case Mcycy = Jcycy - Rcycy can be non-zeros matrices and
* setting obj1.Myy and obj2.Myy to zero matrices.

**Comment by FabricioS** [comment]
Thanks Antoine for this answer and for the improvements.
I got to the same conclusion about the hypothesis Mcycy=0 in the implemented code. However I believe it is not needed for Mcycy to be invertible, but [Identity - m_switch . Mcycy] has to (or, equivalently, (I - Mcycy*m_switch).

I am not sure to understand what this implies about the connected blocks. As far as I understand Mcycy=0 requires that there is no feed-through terms for the involved components, and also no previous coupling between the components to be connected (as past connections of other ports may induce coupling for the present ports). Am I right ?

**Comment by afalaize** [comment]
Yes!  The connection equations to solve for *cy* are
*cy = Mcyx.dxH(x) + Mcyw.z(w) + Mcyy.u + Mcycy.cu,
cu = M_switch.cy,*
that is, what we need is *(Id - Mcycy.M_switch)* to be invertible. Sorry for the imprecision.

And yes, the *implicitness* of the connection propagates as more and more systems are connected. This **can** arise due to the following properties in the subsystems to be connected:
* conservative interconnections of ports with non-zeros *Jyy* matrix (leads to a no-zero Jcycy), or
* resistive interconnections of ports with non-zeros *Jwy* associated with linear dissipatives (since this will lead to a non-zero *Rcycy* after a call to `PHSCore.build_R()` method); for nonlinear dissipatives, this implicitness is solve by the nonlinear solver at each time step.
IMO, the simple, global check for the invertibility of (Id - Mcycy.M_switch) is our best option by the time being; a further generalization would be to consider implicit PHS in image/kernel representation. But this structure was not considered up to now. This is a potential (long time) improvement of the pyphs package.
