### ISSUE TITLE
exploit symmetry in pwl functions

### ISSUE THREAD

**Issue by afalaize** [pyphs/pyphs#32]
Within the dev branch:

```python
>>> from pyphs.examples.pwl.pwl import graph
>>> print(graph.core.H.factor())
-1.0*(-19.52*xstor**2 - 3.33066907387547e-16*xstor*Abs(xstor) - 3.84*xstor*Abs(xstor - 3.2) - 2.88*xstor*Abs(xstor - 2.4) - 1.92*xstor*Abs(xstor - 1.6) - 0.960000000000001*xstor*Abs(xstor - 0.800000000000001) + 0.96*xstor*Abs(xstor + 0.8) + 1.92*xstor*Abs(xstor + 1.6) + 2.88*xstor*Abs(xstor + 2.4) + 3.84*xstor*Abs(xstor + 3.2) + 3.5527136788005e-15*xstor + 12.288*Abs(xstor - 3.2) + 6.912*Abs(xstor - 2.4) + 3.072*Abs(xstor - 1.6) + 0.768000000000001*Abs(xstor - 0.800000000000001) + 0.768*Abs(xstor + 0.8) + 3.072*Abs(xstor + 1.6) + 6.912*Abs(xstor + 2.4) + 12.288*Abs(xstor + 3.2) - 122.88)
```

We see the bottle-neck is the Absolute function. With a symmetric domain, half the evaluations can be saved!

**Comment by afalaize** [comment]
@TristanLbrn?

**Comment by TristanLbrn** [comment]
I suggest to evaluate dissymetry as follows:
`Y_dissym = Y[len(Y)//2::-1] + Y[len(Y)//2:]  `  
Then assert
`all(Y_dissym < np.spacing(1000))`
to check if the dataset is symmetric.

Because of symmetry, the coefficients in Chua & Ying can be calculated with half of the dataset `X = X[len(X)//2:]` and `Y = Y[len(Y)//2:]` and reduce to
```
    b = m[-1]
    a = y0 
  c = 0.5*(m[1:] - m[:P])
```
Then the expression of the piecewise linear function becomes
`expr = a + b*x +sum(c*(abs(x - X) - abs(x + X)))`

I have commited these modifications:
[https://github.com/afalaize/pyphs/commit/3ad81d4a92b03f55d11fcbab0d7e974ad66f6e90](url)

Maybe some feedbacks?

**Comment by afalaize** [comment]
This question will be treated at implementation of PWL system
