### ISSUE TITLE
Parametric analysis

### ISSUE THREAD

**Issue by FabricioS** [pyphs/pyphs#86]
Is there a way to efficiently perform a parametric analysis ?
In other words, perform simulations for a parameter taking sequentially a set of values (one for each simulation) avoiding building objects, methods and generating code for each value ?

**Comment by afalaize** [comment]
This is not possible in pure python simulation, because the symbolic objects are lambdified, i.e. a rebuild is needed to account for any parameter change. Things are different for C++ simulation, because only the file "parameters.cpp" needs to be updated, and the change is accounted for at compilation.

To do so, you can use the "Simulation.init_parameters" method in a loop over your parameters values. It takes a new "Core.subs" dictionary as input and writes the corresponding "parameters.cpp" at the right place. Then, just use the "Simulation.process" method, which begins by the compilation of sources. I just corrected the code to achieve this, tests for the PR #87 are running.

Can you confirm the procedure and close the issue once it's merged?

**Comment by FabricioS** [comment]
Seems OK for C++ simulations (and I don't see the point in having this in Python too, unless you can not compile C++)
Is there a similar procedure to change the initial conditions ?

**Comment by FabricioS** [comment]
While the computations are correct, there is an issue while retrieving the results, for example for posterior manipulation/plotting/etc...
In the loop, I can easily save the results by copying the data folder into another one with explicit name (referring to variable and current value of parametric analysis). However, out of the loop, the Data methods only retrieve results from the config['path']/data folder.
Would it be relevant to add a data_path option in the config, and use it in the methods of the Data class ?

**Comment by afalaize** [comment]
Regarding the initial condition: the init value for specific arguments can be specified as a symbol with corresponding entry in `Simulation.method.subs`. E.g: 
```
# Define a xinit symbol
xinit = core.symbols('xinit')  
# here, dim(x)=2 and we give a symbol for init of x[1] 
inits = {'x': [0., xinit]}  
# give a dummy substitution value for xinit (either it will complain)
simu.method.subs[xinit] = 1. 
#  pass the inits dic to the Simulation.init method
simu.init(u=u, nt=nt, inits=inits) 
```
Then, you can change the value for xinit with the `Simulation.init_parameters` method.

Regarding the location of simulation data, I usually retrieve the results before a new interation in the loop. But Yes, this can be improved. This is related to issue #44.
